version: "2"
linters:
  enable:
    - depguard
    - ginkgolinter
    - govet
    - modernize
    - staticcheck
  settings:
    depguard:
      rules:
        restricted-packages:
          files:
            - $all
          deny:
            - pkg: html/template$
              desc: html/template must not be used
            - pkg: log$
              desc: log must not be used
  exclusions:
    paths:
      - '^gen/'
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cybozu/neco-containers/spiffe-test
  exclusions:
    paths:
      - '^gen/'
