name: Setup cosign
description: "This action installs cosign CLI using fixed version cosign-installer action."
runs:
  using: composite
  steps:
    # cosign-installer requires envsubst command to be installed.
    # However, it does not exist in ubuntu-slim runner.
    # ref: https://github.com/sigstore/cosign-installer/issues/222
    - name: Install envsubst used in cosign-installer action
      shell: bash
      run: |
        if ! command -v envsubst &>/dev/null; then
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            gettext-base
        fi
    - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6  # v4.1.2
    - run: |
        cosign version
      shell: bash
