#!/bin/bash -xe

GITHUB_TOKEN=$1

BIN_DIR=/runner/_work/bin
TMP_DIR=/runner/_work/tmp
mkdir -p ${BIN_DIR} ${TMP_DIR}

curl -o ${TMP_DIR}/latest.json -L -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/cybozu-go/neco/releases/latest"
DOWNLOAD_URL=$(cat ${TMP_DIR}/latest.json | jq -r '.assets[]|select(.name|test("neco-operation-cli-linux_.*"))|.browser_download_url')

curl -o ${TMP_DIR}/necocli.deb -L -H "Authorization: token ${GITHUB_TOKEN}" ${DOWNLOAD_URL}
dpkg -x ${TMP_DIR}/necocli.deb ${TMP_DIR}
mv ${TMP_DIR}/usr/bin/* ${BIN_DIR}

echo ${BIN_DIR} >> $GITHUB_PATH
