name: "Prepare build action"
description: "Prepare parameters for the build job"
inputs:
  dir:
    description: "working directory"
    required: false
    default: ""
  container-image:
    description: "container image"
    required: true
  target:
    description: "target name"
    required: false
    default: ""
  request-scan:
    description: "Request image scanning (true, false, or auto)"
    required: false
    default: "auto"
  github_token:
    description: "GitHub Token"
    required: true
outputs:
  branch:
    description: "branch"
    value: ${{ steps.extract.outputs.branch }}
  tag:
    description: "tag"
    value: ${{ steps.extract.outputs.tag }}
  build:
    description: "build is needed (true or '')"
    value: ${{ steps.flags.outputs.build }}
  push:
    description: "push is needed (true or '')"
    value: ${{ steps.flags.outputs.push }}
  # docker/build-push-action does not accept '' as its push flag
  docker_push:
    description: "push is needed (true or false)"
    value: ${{ steps.flags.outputs.docker_push }}
  scan:
    description: "scan is needed (true or '')"
    value: ${{ steps.scan.outputs.scan }}

runs:
  using: composite
  steps:
    - id: dir
      name: Decide directory
      shell: bash
      run: |
        if [ -z "${{ inputs.dir }}" ]; then
          echo "dir=${{ inputs.container-image }}" >> $GITHUB_OUTPUT
        else
          echo "dir=${{ inputs.dir }}" >> $GITHUB_OUTPUT
        fi
    - id: extract
      name: Extract targets
      shell: bash
      run: |
        DIR=${{ steps.dir.outputs.dir }}
        IMAGE=${{ inputs.container-image }}
        TAG=$(cat ${DIR}/TAG)
        FOUND=$(container-tag-exists ghcr.io/cybozu/${IMAGE} ${TAG})
        # The stdout should be either "" or "found".
        if [ "${FOUND}" = "" ]; then
          echo "tag=ghcr.io/cybozu/${IMAGE}:${TAG}" >> $GITHUB_OUTPUT

          if [ -f ${DIR}/BRANCH ]; then
            if echo ${TAG} | grep -q -e - ; then
              echo ===== Skip pushing branch tags for pre-release ${TAG} =====
            else
              BRANCH=$(cat ${DIR}/BRANCH)
              echo "branch=ghcr.io/cybozu/${IMAGE}:${BRANCH}" >> $GITHUB_OUTPUT
            fi
          fi
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - id: flags
      name: Decide build flags
      shell: bash
      run: |
        if ! [ -z "${{ steps.extract.outputs.tag }}" ]; then
          echo "build=true" >> $GITHUB_OUTPUT
          if [ "${EVENT_NAME}" != "pull_request" ]; then
            echo "push=true" >> $GITHUB_OUTPUT
            echo "docker_push=true" >> $GITHUB_OUTPUT
          else
            echo "docker_push=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "docker_push=false" >> $GITHUB_OUTPUT
        fi
      env:
        EVENT_NAME: ${{ github.event_name }}
    - id: scan-pre
      name: Decide scan flag
      shell: bash
      working-directory: ${{ steps.dir.outputs.dir }}
      run: |
        # Check if scan-mode is manually overridden
        echo "inputs.request-scan is: ${{ inputs.request-scan }}"
        if [ -z "${{ inputs.request-scan }}" ]; then
          echo "Calculating scanning mode..."
        elif [ "${{ inputs.request-scan }}" = "auto" ]; then
          echo "Calculating scanning mode..."
        elif [ "${{ inputs.request-scan }}" = "true" ]; then
          echo "Scanning is enabled manually."
          echo "scan=true" >> $GITHUB_OUTPUT
          exit 0
        elif [ "${{ inputs.request-scan }}" = "false" ]; then
          echo "Scanning is disabled manually."
          exit 0
        else
          echo "inputs.request-scan has an invalid value"
          exit 1
        fi

        # If base image is substituted by a variable, automatic detection is disabled
        # It instructs users to set scan-flag manually if missing
        if grep FROM Dockerfile | grep -F '$'; then
          echo "!! FROM command may use a base image substituted by a variable."
          echo "!! Please set scan requirement manually."
          exit 1
        fi

        # Skip Trivy scan if scratch-based image
        if [ -z "${{ inputs.target }}" ]; then
          if grep FROM Dockerfile | tail -n 1 | grep scratch; then
            echo "Scanning is disabled for scratch-based images."
            exit 0
          fi
        elif grep FROM Dockerfile | grep AS | grep "${{ inputs.target }}" | grep scratch; then
          echo "Scanning is disabled for scratch-based images."
          exit 0
        fi
        echo "Scanning is enabled at image uploading."
        echo "scan=true" >> $GITHUB_OUTPUT
    - id: scan
      name: Enable scan for upload-time only
      if: ${{ steps.flags.outputs.push }}
      shell: bash
      run: |
        if [ "${{ steps.scan-pre.outputs.scan }}" = "true" ]; then
          echo "scan=true" >> $GITHUB_OUTPUT
        fi
    - name: Validate consistency between BRANCH and TAG
      shell: bash
      run: |
        DIR=${{ steps.dir.outputs.dir }}
        if [ -e "${DIR}/NO_TAG_BRANCH_CONSISTENCY" ]; then exit 0; fi
        ./tag_branch_consistency ${DIR}
    - name: Echo output
      shell: bash
      run: |
        echo
        echo "vvvvvvvvvv vvvvvvvvvv vvvvvvvvvv vvvvvvvvvv vvvvvvvvvv vvvvvvvvvv"
        echo "    Build Policy:"
        echo
        echo "         branch: ${{ steps.extract.outputs.branch }}"
        echo "            tag: ${{ steps.extract.outputs.tag }}"
        echo "          build: ${{ steps.flags.outputs.build }}"
        echo "           push: ${{ steps.flags.outputs.push }}"
        echo "    docker_push: ${{ steps.flags.outputs.docker_push }}"
        echo "           scan: ${{ steps.scan.outputs.scan }}"
        echo ^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^^^^^ ^^^^^^^^^^
        echo
