version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/ceph-extra-exporter"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 14
