name: "Setup env"
description: "setup environment"

inputs:
  platforms:
    description: "target platforms for docker build (setup qemu for non-native platforms)"
  go-version:
    description: "Go version"
  go-version-file:
    description: "Go version file"
  takumi-guard-bot-id:
    description: "Takumi Guard bot ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup QEMU
      # Setup QEMU for non-native platforms (e.g., linux/arm64 on linux/amd64)
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      with:
        platforms: ${{ inputs.platforms }}
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Setup golang
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
    - name:  Setup Takumi Guard
      uses: flatt-security/setup-takumi-guard-golang@37631ecffa6faf06754444a4807451b7a55c64b5 # v1.2.0
      with:
        bot-id: ${{ inputs.takumi-guard-bot-id }}
    - name: Setup tools with aqua
      uses: ./.github/actions/aqua
