name: "Setup env"
description: "setup environment"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  go-version:
    description: "Go version"
  go-version-file:
    description: "Go version file"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64/v8
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}
    - name: Setup golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
    - name: Install container-tag-exists
      shell: bash
      run: go install github.com/Hsn723/container-tag-exists@latest
