#!/bin/bash -e

if [ -z "${PR}" ]; then
    echo 'Please supply ${PR}.'
    exit 1
fi

mkdir -p .github/outputs
gh pr view "${PR}" --json files | jq -r '.files[].path' | egrep -v '[.]md$' | xargs -n1 printf "$(pwd)/%s\n" | sort > .github/outputs/__diff.txt

echo "Changed Files:"
cat .github/outputs/__diff.txt | jq -n --raw-input '[inputs]' | yq -P

MATRIX_FILE="${MATRIX_FILE:-.github/build-targets.yaml}"
JSON_MATRIX="$(yq -ojson '.' "${MATRIX_FILE}")"
OUTPUT_MATRIX='[]'
for i in $(seq $(echo "${JSON_MATRIX}" | jq length)); do
    ENTRY=$(echo "${JSON_MATRIX}" | jq ".[$i - 1]")
    CONTAINER_DIR=$(echo "${ENTRY}" | jq -r '.dir')
    CONTAINER_NAME=$(echo "${ENTRY}" | jq -r '."container-image"')
    echo "Checking ${CONTAINER_NAME}..."
    if grep -F $(realpath "${CONTAINER_DIR}")'/' .github/outputs/__diff.txt > /dev/null; then
        PLAN=$(./build_decision "${MATRIX_FILE}" "${CONTAINER_NAME}")
        if [ "$(echo "${PLAN}" | jq -r '.build')" = "true" ]; then
            OUTPUT_MATRIX="$(jq -nc '[inputs] | flatten' <(echo "${OUTPUT_MATRIX}") <(echo "[${PLAN}]"))"
            echo '  build'
        else
            echo '  skip (tag already exists)'
        fi
    else
        echo '  skip (no changes)'
    fi
done

echo "Result:"
echo "${OUTPUT_MATRIX}" | yq -P

# Render matrix
echo "${OUTPUT_MATRIX}" | jq -c > .github/outputs/__matrix.json
