#!/bin/sh -e

if [ $# -eq 0 ]; then
    echo "Usage: tag_exists NAME"
    exit 1
fi

API=https://quay.io/api/v1
NAME="$1"
if [ $# -ge 2 ]; then
    DIR="$2"
    if [ $# -ge 3 ]; then
        SUFFIX="$3"
    else
        SUFFIX=""
    fi
else
    DIR="$NAME"
fi
TAG=$(cat "$DIR"/TAG)$SUFFIX
RESPONSE=$(curl -sSfL "$API/repository/cybozu/$NAME/tag/?specificTag=$TAG&onlyActiveTags=true")
NUM=$(echo "$RESPONSE" | jq '.tags | length')

if [ $NUM -gt 0 ]; then
    echo "ok"
    exit 0
fi

echo "ng"
