#!/bin/sh -e

if [ $# -eq 0 ]; then
    echo "Usage: tag_branch_consistency DIR"
    exit 1
fi

DIR="$1"

if [ ! -f ${DIR}/BRANCH ]; then
    echo "Skip because BRANCH not found"
    exit 0
fi

TAG=$(cat "${DIR}"/TAG)
BRANCH=$(cat ${DIR}/BRANCH | xargs)

for b in $BRANCH; do
  if [ ${TAG} != $(echo ${b}$(echo ${TAG} | sed -e s/${b}//)) ]; then
      echo "TAG: ${TAG} and BRANCH: ${b} diverge"
      exit 1
  fi
done

exit 0
