#!/bin/sh -e

if [ $# -eq 0 ]; then
    echo "Usage: tag_branch_consistency DIR"
    exit 1
fi

DIR="$1"

if [ ! -f ${DIR}/BRANCH ]; then
    echo "Skip because BRANCH not found"
    exit 0
fi

TAG=$(cat "${DIR}"/TAG)
BRANCH=$(tr '\n' ' ' < "${DIR}/BRANCH")
SKIP_BRANCHES="${DIR}/NO_TAG_BRANCH_CONSISTENCY"

for b in $BRANCH; do
  if [ -e "${SKIP_BRANCHES}" ] && grep -x "${b}" "${SKIP_BRANCHES}"; then
      echo "Skipped consistency check for BRANCH: ${b} (listed in ${SKIP_BRANCHES})"
      continue
  fi

  if [ ${TAG} != $(echo ${b}$(echo ${TAG} | sed -e s/${b}//)) ]; then
      echo "TAG: ${TAG} and BRANCH: ${b} diverge"
      exit 1
  fi
done

exit 0
