name: "Build and push"
description: "build and push container image"

inputs:
  dir:
    description: "working direcotry"
    required: false
    default: ""
  container-image:
    description: "container image"
    required: true
  github_token:
    description: "GitHub Token"
    required: true
  yamory_token:
    description: "Yamory Access Token"
    required: true
  platforms:
    description: "Target platforms"
    required: false
    default: ""
  load:
    description: "Load built image to local docker daemon"
    required: false
    default: ""
  make-targets:
    description: "make targets before building docker image"
    required: false
    default: ""
  make-post-targets:
    description: "make targets after building docker image"
    required: false
    default: ""
  request-scan:
    description: "Request image scanning (true, false, or auto)"
    required: false
    default: "auto"
  target:
    description: "Target stage to build"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: prepare
      name: Prepare build parameters
      uses: ./.github/actions/prepare_build_params
      with:
        dir: ${{ inputs.dir }}
        container-image: ${{ inputs.container-image }}
        platforms: ${{ inputs.platforms }}
        load: ${{ inputs.load }}
        target: ${{ inputs.target }}
        request-scan: ${{ inputs.request-scan }}
        github_token: ${{ inputs.github_token }}
    - name: Make pre-targets
      if: ${{ inputs.make-targets != '' && steps.prepare.outputs.build }}
      shell: bash
      run: |
        for i in ${{ inputs.make-targets }}; do
          echo "Executing make $i..."
          make -C ${{ inputs.dir }} $i
        done
    - name: Build
      if: ${{ steps.prepare.outputs.build }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.dir }}
        platforms: ${{ steps.prepare.outputs.platforms }}
        load: ${{ steps.prepare.outputs.load }}
        provenance: false
        push: false
        tags: |
          ${{ steps.prepare.outputs.tag }}
          ${{ steps.prepare.outputs.branch }}
        target: ${{ inputs.target }}
    - name: Make post-targets
      if: ${{ inputs.make-post-targets != '' && steps.prepare.outputs.build }}
      shell: bash
      env:
        IMAGE_TAG: ${{ steps.prepare.outputs.tag }}
      run: |
        for i in ${{ inputs.make-post-targets }}; do
          echo "Executing make $i..."
          make -C ${{ inputs.dir }} $i
        done
    - name: Push
      if: ${{ steps.prepare.outputs.push }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.dir }}
        platforms: ${{ steps.prepare.outputs.platforms }}
        provenance: false
        push: ${{ steps.prepare.outputs.docker_push }}
        tags: |
          ${{ steps.prepare.outputs.tag }}
          ${{ steps.prepare.outputs.branch }}
        target: ${{ inputs.target }}
    - name: Scan images
      if: ${{ steps.prepare.outputs.scan }}
      uses: ./.github/actions/trivy_scan
      with:
        dir: ${{ inputs.dir }}
        container-image: ${{ inputs.container-image }}
        tag: ${{ steps.prepare.outputs.tag }}
        yamory_token: ${{ inputs.yamory_token }}
