kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v1.16.3"
  networking:
    serviceSubnet: 10.68.0.0/16
    podSubnet: 10.64.0.0/14
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NamespaceLifecycle,LimitRanger,ServiceAccount,Priority,DefaultTolerationSeconds,DefaultStorageClass,PersistentVolumeClaimResize,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction"
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /mnt/host/scheduler
      hostPath: /tmp/kindtest/scheduler
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
