name: "Build ceph"
description: "Build ceph"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - name: Setup build environment
      uses: ./.github/actions/setup
      with:
        github_token: ${{ inputs.github_token }}
    - id: prepare
      name: Prepare build parameters
      uses: ./.github/actions/prepare_build_params
      with:
        container-image: ceph
        github_token: ${{ inputs.github_token }}
    - name: Build
      if: ${{ steps.prepare.outputs.build }}
      shell: bash
      run: |
        TAG_CONTENT=$(cat TAG)
        if ! echo "${TAG_CONTENT}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "Invalid TAG file format: ${TAG_CONTENT}"
          exit 1
        fi
        VERSION=$(echo "${TAG_CONTENT}" | cut -d '.' -f1-3)
        sudo ./build.sh ${VERSION}
        sudo mv src/workspace .
      working-directory: ceph
    - name: Build and push
      if: ${{ steps.prepare.outputs.build }}
      uses: docker/build-push-action@v6
      with:
        context: ceph
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.prepare.outputs.docker_push }}
        # Input comma-separated tags: <tag>,<branch1>,<branch2>,...
        tags: ${{ steps.prepare.outputs.tag }}${{ steps.prepare.outputs.branch && format(',{0}', steps.prepare.outputs.branch) }}
