apiVersion: apps/v1
kind: Deployment
metadata:
  name: cep-checker
  namespace: kube-system 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cep-checker 
  template:
    metadata:
      labels:
        app: cep-checker 
    spec:
      containers:
      - image: ghcr.io/cybozu/cep-checker:dev
        name: cep-checker
        ports:
        - containerPort: 8080
      serviceAccountName: cep-checker
---
apiVersion: v1
kind: Service
metadata:
  name: cep-checker-metrics 
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app: cep-checker
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cep-checker
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cep-checker
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cep-checker
subjects:
  - kind: ServiceAccount
    name: cep-checker
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cep-checker 
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - "cilium.io"
  resources:
  - ciliumendpoints
  verbs:
  - get
  - list
