apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ghcr.io/cybozu/ubuntu:22.04
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    sysctls:
    - name: net.ipv4.ping_group_range
      value: 0 10000
  restartPolicy: Always