apiVersion: v1
kind: ServiceAccount
metadata:
  name: machines-endpoints
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machines-endpoints
rules:
  - apiGroups: [""]
    resources:
      - services
      - configmaps
    verbs: ["patch", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "patch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machines-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machines-endpoints
subjects:
  - kind: ServiceAccount
    name: machines-endpoints
    namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: machines-endpoints-cronjob
  labels:
    cronjob: machines-endpoints-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: machines-endpoints
              image: ghcr.io/cybozu/machines-endpoints:2.0.0
              imagePullPolicy: IfNotPresent
              args:
                - --sabakan-address=<SABAKAN_ADDRESS>:10080  # replace with the sabakan address and its GraphQL port
                - --all-servers-port=9100:node-exporter
                - --boot-servers-port=2381:etcd-metrics
                - --bmc-reverse-proxy-configmap
                - --bmc-log-collector-configmap
          restartPolicy: OnFailure
          serviceAccountName: machines-endpoints
