apiVersion: v1
kind: ConfigMap
metadata:
  namespace: contour
  name: necosen-free-config
data:
  config.yaml: |
    sourceIP:
      allowedCIDRs: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: contour
  name: necosen-free
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: necosen-free
  template:
    metadata:
      labels:
        app.kubernetes.io/name: necosen-free
    spec:
      containers:
      - name: necosen
        image: necosen:dev
        command:
          - /necosen
          - --reflection=true
          - --log-level=debug
        volumeMounts:
        - mountPath: /etc/necosen
          name: necosen-config
      volumes:
      - configMap:
          name: necosen-free-config
        name: necosen-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: contour
  name: necosen-free
spec:
  selector:
    app.kubernetes.io/name: necosen-free
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
---
apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  namespace: contour
  name: necosen-free
spec:
  services:
  - name: necosen-free
    port: 50051
  protocol: h2c # Test plain communication
