apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: contour
  name: necosen
spec:
  dnsNames:
  - necosen
  issuerRef:
    kind: ClusterIssuer
    name: cluster-ca
  secretName: necosen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: contour
  name: necosen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: necosen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: necosen
    spec:
      containers:
      - name: necosen
        image: necosen:dev
        command:
          - /necosen
          - --log-level=debug
          - --tls-cert-file=/etc/secrets/tls.crt
          - --tls-key-file=/etc/secrets/tls.key
        volumeMounts:
        - mountPath: /etc/necosen
          name: necosen-config
        - mountPath: /etc/secrets
          name: tls
      volumes:
      - configMap:
          name: necosen-config
        name: necosen-config
      - secret:
          secretName: necosen
        name: tls
---
apiVersion: v1
kind: Service
metadata:
  namespace: contour
  name: necosen
spec:
  selector:
    app.kubernetes.io/name: necosen
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
---
apiVersion: projectcontour.io/v1alpha1
kind: ExtensionService
metadata:
  namespace: contour
  name: necosen
spec:
  services:
  - name: necosen
    port: 50051
  protocol: h2 # Test encrypted communication
