- dir: "./spiffe-test"
  container-image: "spiffe-test-server"
  target: "server"
  make-targets: "check"
  scan:
    enabled: false
- dir: "./spiffe-test"
  container-image: "spiffe-test-client"
  target: "client"
  make-targets: "check"
  scan:
    enabled: false
