- dir: "./squid"
  container-image: "squid"
  target: "squid"
  scan:
    enabled: false
- dir: "./squid"
  container-image: "squid-dev"
  target: "squid-dev"
  scan:
    enabled: true
    team: neco
