- dir: "./victoriametrics-operator"
  container-image: "victoriametrics-operator"
  target: "operator"
  scan:
    enabled: false
- dir: "./victoriametrics-operator"
  container-image: "victoriametrics-config-reloader"
  target: "config-reloader"
  scan:
    enabled: false
