name: "Build Cilium Image Tools"
description: "Build tools which are used to build Cilium images"
inputs:
  image-tools_version:
    description: "cilium/image-tools version"
    required: true
runs:
  using: composite
  steps:
  - name: Install dependencies
    shell: bash
    env:
      DEBIAN_FRONTEND: noninteractive
    run: |
      sudo apt-get -q update
      sudo ln -fs /usr/share/zoneinfo/UTC /etc/localtime
      sudo apt-get -q install -y --no-install-recommends \
        python2 \
        llvm
      sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 2

  - name: Download cilium/image-tools
    shell: bash
    run: |
      mkdir -p cilium/src/workspace/bin cilium/src/workspace/usr/local/bin cilium/src/workspace/usr/lib cilium/src/image-tools
      curl -sSLf https://github.com/cilium/image-tools/archive/${{ inputs.image-tools_version }}.tar.gz | \
        tar zxf - --strip-components 1 -C cilium/src/image-tools

  - name: Install dependencies
    shell: bash
    working-directory: cilium/src/image-tools/images/compilers
    run: |
      # https://github.com/cilium/image-tools/blob/master/images/compilers/install-deps.sh
      PACKAGES_FROM=$(grep -n packages= install-deps.sh | cut -d: -f1 | jq '. + 1')
      PACKAGES_TO=$(grep -n ')' install-deps.sh | cut -d: -f1 | jq -n "[inputs | select(. >= ${PACKAGES_FROM})] | min - 1")
      PACKAGES=$(cat install-deps.sh | sed -n ${PACKAGES_FROM},${PACKAGES_TO}p | awk '{ print $1 }' | grep -v arm64 | tr '\n' ' ')
      sudo apt-get -q install -y --no-install-recommends ${PACKAGES}

      PACKAGES_FROM=$(grep -n packages_amd64= install-deps.sh | cut -d: -f1 | jq '. + 1')
      PACKAGES_TO=$(grep -n ')' install-deps.sh | cut -d: -f1 | jq -n "[inputs | select(. >= ${PACKAGES_FROM})] | min - 1")
      PACKAGES=$(cat install-deps.sh | sed -n ${PACKAGES_FROM},${PACKAGES_TO}p | awk '{ print $1 }' | grep -v arm64 | tr '\n' ' ')
      sudo apt-get -q install -y --no-install-recommends ${PACKAGES}

  - name: Build llvm
    shell: bash
    run: |
      WORKSPACE=$(pwd)/cilium/src/workspace
      cd cilium/src/image-tools
      sudo images/llvm/checkout-llvm.sh
      
      # images/llvm/build-llvm-native.sh
      sudo mkdir -p /src/llvm/llvm/build-native
      cd /src/llvm/llvm/build-native
      sudo cmake .. -G "Ninja" \
          -DLLVM_TARGETS_TO_BUILD="BPF" \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DBUILD_SHARED_LIBS="OFF" \
          -DCMAKE_BUILD_TYPE="Release" \
          -DLLVM_BUILD_RUNTIME="OFF" \
          -DCMAKE_INSTALL_PREFIX="/usr/local" \
          -DLLVM_ENABLE_Z3_SOLVER="OFF"
      sudo ninja clang llc llvm-objcopy
      sudo strip bin/clang
      sudo strip bin/llc
      sudo strip bin/llvm-objcopy
      sudo mkdir -p /out/linux/amd64/bin
      sudo cp bin/clang bin/llc bin/llvm-objcopy /out/linux/amd64/bin

      sudo mv /out/linux/amd64/bin/clang /out/linux/amd64/bin/llc /out/linux/amd64/bin/llvm-objcopy ${WORKSPACE}/bin/

  - name: Build bpftool
    shell: bash
    run: |
      # https://github.com/libbpf/bpftool/tree/main?tab=readme-ov-file#build-bpftool
      WORKSPACE=$(pwd)/cilium/src/workspace
      cd cilium/src/image-tools
      sudo images/bpftool/checkout-linux.sh
      sudo bash -c 'echo ${PATH}'
      sudo which clang
      sudo clang --version
      ldconfig -v 2>/dev/null || true
      sudo bash -c "echo ${WORKSPACE}"
      sudo bash -c "echo ${PATH}"
      sudo bash -c "PATH=${WORKSPACE}/bin:${PATH} sudo which clang"
      sudo bash -c "PATH=${WORKSPACE}/bin:${PATH} sudo clang --version"
      sudo bash -c "PATH=${WORKSPACE}/bin:${PATH} EXTRA_CFLAGS=-v images/bpftool/build-bpftool-native.sh"
      ldd /out/linux/amd64/bin/bpftool
      sudo mv /out/linux/amd64/bin/bpftool ../workspace/usr/local/bin/
