#!/bin/sh -xe

git clone -b ${NECO_BRANCH:-release} https://github.com/cybozu-go/neco.git ${NECO_DIR}
make -C ${NECO_DIR} clean
make -C ${NECO_DIR}/dctest setup
make -C ${NECO_DIR}/dctest run-placemat-inside-container MENU_ARG=menu-ss.yml
make -C ${NECO_DIR}/dctest test SUITE=bootstrap
