#!/bin/sh -xe

set +x
if [ -n "${GITHUB_USER}" -a -n "${GITHUB_TOKEN}" ]; then
    USER_PASS="${GITHUB_USER}:${GITHUB_TOKEN}@"
fi
git clone -b ${NECO_APPS_BRANCH:-release} https://${USER_PASS}github.com/cybozu-go/neco-apps.git ${NECO_APPS_DIR}
set -x

cp /secrets/account.json ${NECO_APPS_DIR}/test/

make -C ${NECO_APPS_DIR}/test setup
make -C ${NECO_APPS_DIR}/test dctest SUITE=bootstrap OVERLAY=neco-dev
