#!/bin/sh -e

DEST=/host

cp --remove-destination /usr/local/argocd/bin/argocd $DEST/argocd
cp --remove-destination /usr/local/argocd/bin/kubectl $DEST/kubectl
cp --remove-destination /usr/local/argocd/bin/kustomize $DEST/kustomize
chmod 755 $DEST/argocd
chmod 755 $DEST/kubectl
chmod 755 $DEST/kustomize
