name: "Build admission"
description: "Build admission"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - name: Setup build environment
      uses: ./.github/actions/setup
      with:
        github_token: ${{ inputs.github_token }}
        go-version-file: admission/go.mod
    - id: prepare
      name: Prepare build parameters
      uses: ./.github/actions/prepare_build_params
      with:
        dir: admission
        container-image: neco-admission
        github_token: ${{ inputs.github_token }}
    - name: Test
      if: ${{ steps.prepare.outputs.build }}
      shell: bash
      run: |
        make check-generate
        make test
      working-directory: admission
    - name: Build and push
      if: ${{ steps.prepare.outputs.build }}
      uses: docker/build-push-action@v5
      with:
        context: admission
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.prepare.outputs.docker_push }}
        tags: |
          ${{ steps.prepare.outputs.tag }}
          ${{ steps.prepare.outputs.branch }}
